meta_product_name: "RPUW"
meta_title: "Requête Pour Un Winner"
meta_description: "Jouez avec vos amis au jeu mythique de votre enfance"
meta_image: "logo_rpuw.png" # exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
